# https://github.com/antfu/static/blob/master/.github/workflows/scheduler.yml
name: Sponsorkit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches: [ main ]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update sponsors
        run: npm i && npm run build
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}

      - name: Commit
        uses: EndBug/add-and-commit@v5
        with:
          message: "chore: update sponsors.svg"
          add: "sponsors.*svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
