name: Widgets

on:
  schedule:
    - cron: '0 */24 * * *'
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[stop]')"
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Create README.md
      uses: actions-js/profile-readme@master
      with:
        username: GeopJr
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: gautamkrishnar/blog-post-workflow@master
      with:
        feed_list: "https://dev.to/feed/geopjr"
        template: "$newline - $randomEmoji(💖,🦄,🔖) [$title]($url)"
        gh_token: ${{ secrets.TOKEN }}
        commit_message: "Updated with the latest blog posts [stop]"